import MetricCard from './MetricCard';

export default function MetricsGrid({ analysisResult, refExists }) {
  if (!analysisResult) return null;

  const totalFields = Object.keys(analysisResult.fields || {}).length;
  const forgedCount = analysisResult.forged_fields?.length || 0;

  return (
    <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
      <MetricCard
        label="Is AI-Generated?"
        value={analysisResult.ela_is_ai_generated ? 'Likely generated by AI' : 'Not Likely'}
        status={analysisResult.ela_is_ai_generated ? 'bad' : 'good'}
      />
      <MetricCard
        label="Is Reference Number already used?"
        value={refExists ? 'Yes' : 'NO'}
        status={refExists ? 'bad' : 'good'}
      />
      <MetricCard
        label="Fields Verified"
        value={`${totalFields - forgedCount}/${totalFields} passed`}
        status={forgedCount === 0 ? 'good' : 'bad'}
      />
      <MetricCard
        label="Analysis Time"
        value={`${(analysisResult.duration_ms / 1000).toFixed(1)}s`}
        status="good"
      />
    </div>
  );
}
